[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
rust-version = "1.88"
edition = "2024"
authors = ["Markus Zehnder"]
license = "MIT or Apache-2.0"
repository = "https://github.com/zehnm/aoostar-rs"
